JeonsiLog/app/build.gradle, JeonsiLog/app/src/main/AndroidManifest.xml, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/RetrofitClient.kt
Title: Retrofit Client 
Jira Ticket: ISSUE-5
<br>
build.gradle -> retrofit2, gson 추가
utils -> RetrofitClient 추가
=> [PR] develop <- ISSUE-5_feat/#5-RetrofitClient

JeonsiLog/app/build.gradle, JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/MyGlideApp.kt, JeonsiLog/build.gradle
Title: GlideApp
Jira Ticket: ISSUE-14
<br>
build.gradle -> Glide 추가
utils -> GlideApp 생성
=> [PR] develop <- ISSUE-14_feat/#7-GlideApp

JeonsiLog/app/build.gradle, JeonsiLog/app/src/main/java/com/example/jeonsilog/base/BaseFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/HomeFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MyPageFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/NotificationFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/PhotoCalendarFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/SearchFragment.kt, JeonsiLog/app/src/main/res/layout/activity_main.xml, JeonsiLog/app/src/main/res/layout/fragment_home.xml, JeonsiLog/app/src/main/res/layout/fragment_my_page.xml, JeonsiLog/app/src/main/res/layout/fragment_notification.xml, JeonsiLog/app/src/main/res/layout/fragment_photo_calendar.xml, JeonsiLog/app/src/main/res/layout/fragment_search.xml, JeonsiLog/app/src/main/res/values/font_style.xml
Title: ResourceSetting
Jira Ticket: ISSUE-4 
<br>
BaseFragment -> DataBinding으로 변경
FontStyle -> 행간 있는 버전 추가
=> [PR] develop <- ISSUE-4-feat/#12-ResourseSetting

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/HomeFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt
Title: Main Page Setting
Jira Ticket: ISSUE-15 
<br>
Bottom Navigation SetStateBn 함수 추가
=> [PR] develop <- ISSUE-15-feat/#8-MainPageSetting

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/CalendarApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReplyApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReportApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/calendar/GetMyPhotoResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/calendar/PostPhotoFromGalleryRequest.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/calendar/PostPhotoFromPosterRequest.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/GetReplyResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/PostReplyRequest.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/PostReportRequest.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/report/GetReportsResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/calendar/CalendarRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/calendar/CalendarRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/reply/ReplyRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/reply/ReplyRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/report/ReportRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/report/ReportRepositoryImpl.kt
Title: API#2
Jira Ticket: ISSUE-31 
<br>
- 포토캘린더 API
- 댓글 API
- 신고 API
=> [PR] develop <- ISSUE-31-feat/#39-API#2

JeonsiLog/app/src/main/AndroidManifest.xml, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/FollowApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowerResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/follow/FollowRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/follow/FollowRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserCalendarFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserCalendarRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFollowerFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFollowingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListVpAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRatingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserVpAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserCalendarViewModel.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserViewModel.kt, JeonsiLog/app/src/main/res/layout/fragment_other_user_calendar.xml, JeonsiLog/app/src/main/res/layout/fragment_other_user_list.xml, JeonsiLog/app/src/main/res/layout/fragment_other_user_list_follower.xml, JeonsiLog/app/src/main/res/layout/fragment_other_user_list_following.xml, JeonsiLog/app/src/main/res/layout/item_other_user_list_follow.xml, JeonsiLog/app/src/main/res/layout/item_other_user_rating.xml
Title: OtherUserProfile
Jira Ticket: ISSUE-32
<br>
타 유저 페이지 서버 연결
=> [PR] develop <- ISSUE-32-feat/#41-OtherUserProfilePage

JeonsiLog/app/build.gradle, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/PlaceApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/GetReplyResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/place/PlaceRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionReplyRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionReviewRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExtraActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/PosterFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/PosterVpAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoItemAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceItemAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionViewModel.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ReviewViewModel.kt, JeonsiLog/app/src/main/res/layout/fragment_exhibition.xml, JeonsiLog/app/src/main/res/layout/fragment_exhibition_place.xml, JeonsiLog/app/src/main/res/layout/fragment_review.xml, JeonsiLog/app/src/main/res/layout/item_exhibition_place.xml, JeonsiLog/app/src/main/res/layout/item_exhibition_review.xml, JeonsiLog/app/src/main/res/navigation/nav_exhibition.xml, JeonsiLog/app/src/main/res/values/strings.xml
Title: API Exhibition Page
Jira Ticket: ISSUE-30
<br>
전시회 페이지 API 작업
=> [PR] develop <- ISSUE-30-feat/#43-API-ExhibitionPage

JeonsiLog/app/build.gradle, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/RetrofitClient.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageSettingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchItemAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserViewModel.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/SpannableStringUtil.kt, JeonsiLog/app/src/main/res/layout/fragment_my_page.xml, JeonsiLog/app/src/main/res/layout/fragment_my_page_list.xml, JeonsiLog/app/src/main/res/layout/fragment_other_user.xml, JeonsiLog/app/src/main/res/layout/fragment_other_user_list.xml, JeonsiLog/app/src/main/res/layout/item_my_page_interest.xml
Title: DETAIL-Profile 
Jira Ticket: ISSUE-36
<br>
전시회 키워드 부분 수정
탭 밑에 회색 바 추가
환경설정 앱 버전 BuildConfig 참조하도록 수정
타 유저 프로필에서 팔로우, 언팔로우 시 바로 반영 안되는 문제 수정
유저 검색, 팔로잉 목록, 팔로우 목록 -> 마이페이지 / 타 유저 프로필
=> [PR] develop <- ISSUE-36-mod/#52-DETAIL-Profile

JeonsiLog/app/src/main/AndroidManifest.xml, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/NetworkInterceptor.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/RetrofitClient.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/extension/NetworkDialog.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/extension/NetworkManager.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/GlobalApplication.kt, JeonsiLog/app/src/main/res/layout/dialog_network.xml, JeonsiLog/app/src/main/res/values/strings.xml
Title: NetworkManager
Jira Ticket: ISSUE-40
<br>
- Manifest - ACCESS_NETWORK_STATE 권한 추가
- Network State 검사 함수 추가
- NetworkInterceptor 추가
- 네트워크 연결 False 시 보일 Dialog 추가
- 재연결 시 View 새로고침 로직 추가
=> [PR] develop <- ISSUE-40-feat/#62-NetworkManager

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordSearchFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchResultFragment.kt, JeonsiLog/app/src/main/res/layout/fragment_exihibition_info.xml, JeonsiLog/app/src/main/res/layout/fragment_search_exhibition_place.xml, JeonsiLog/app/src/main/res/layout/fragment_search_record.xml, JeonsiLog/app/src/main/res/layout/fragment_search_result.xml, JeonsiLog/app/src/main/res/layout/fragment_user_search.xml
Title: SearchPage
Jira Ticket: ex) ISSUE-42
<br>
SearchPage 네트워크 상태 체크
<br>
=> [PR] develop <- ISSUE-42-feat/#66-NETWORK-SearchPage

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadBottomDialog.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageDialog.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/PhotoCalendarFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/SingleFragment.kt
Title: PhotoCalendarPage
Jira Ticket: SSUE-43
<br>
PhotoCalendarPage 네트워크 상태 체크 기능추가
<br>
=> [PR] develop <- ISSUE-43-feat/#67NETWORK-PhotoCalendarPage

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/UserApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/user/GetIsOpenResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserCalendarFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserCalendarViewModel.kt
Title: MOD-OtherUser
Jira Ticket: ISSUE-47
<br>
- User API - 캘린더 공개 여부에 대한 API 추가
- 타유저 페이지에서 캘린더 공개 여부 확인 과정 수정
=> [PR] develop <- ISSUE-47-mod/#79-MOD-OtherUser

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/TosFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/SignUpViewModel.kt, JeonsiLog/app/src/main/res/drawable/custom_check_box.xml, JeonsiLog/app/src/main/res/drawable/ic_checkbox_blank.xml, JeonsiLog/app/src/main/res/drawable/ic_checkbox_checked.xml, JeonsiLog/app/src/main/res/layout/fragment_tos.xml, JeonsiLog/app/src/main/res/values/strings.xml, JeonsiLog/app/src/main/res/values/themes.xml
Title: MOD-Permission
Jira Ticket: ISSUE-49 
<br>
- string.xml - 권한 재요청 라이팅 수정
- 약관 동의 - 권한 요청 로직 수정
- 약관 동의 레이아웃 수정
=> [PR] develop <- ISSUE-49-mod/#83-MOD-Permission

JeonsiLog/app/src/main/AndroidManifest.xml, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/login/SignUpFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt
Title: FIX-Permission 
Jira Ticket: ISSUE-50
<br>
- 권한 체크 로직 수정
- 권한 재요청 로직 수정
- Manifest.xml 수정
- SignUp & MyPage - 프로필 사진 변경 시 권한 재요청 추가
=> [PR] develop <- ISSUE-50-fix/#85-FIX-Permission

JeonsiLog/app/src/main/AndroidManifest.xml, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/FollowApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/InterestApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/RatingApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReviewApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowerResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/follow/FollowRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/follow/FollowRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/interest/InterestRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/interest/InterestRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/rating/RatingRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/rating/RatingRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageInterestFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowerFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRatingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFollowerFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFollowingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRatingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserViewModel.kt
Title: MOD-Profile
Jira Ticket: ISSUE-52
<br>
마이페이지
별점 페이지 처리
감상평 페이지 처리
즐겨찾기 페이지 처리
팔로우, 팔로잉 페이지 처리
타유저
별점 페이지 처리
감상평 페이지 처리
팔로우, 팔로잉 페이지 처리
=> [PR] develop <- ISSUE-52-mod/#88-MOD-Profile

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ExhibitionApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/exhibition/GetCalendarExhibitionResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/exhibition/SearchResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/exhibition/ExhibitionRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/exhibition/ExhibitionRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/CalendarBottomDialog.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadBottomDialog.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageDialog.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/PhotoCalendarFragment.kt, JeonsiLog/app/src/main/res/drawable/layer_rounded_dialog.xml, JeonsiLog/app/src/main/res/drawable/shape_dialog_dimming_zone.xml, JeonsiLog/app/src/main/res/layout/view_calendar_dialog.xml, JeonsiLog/app/src/main/res/layout/view_load_dialog.xml, JeonsiLog/app/src/main/res/values/colors.xml
Title: PhotoCalendar
Jira Ticket: ex) ISSUE-54
<br>
- 포토캘린더 전시회 검색 페이징 처리
- 공개/비공개 처리 
<br>
=> [PR] develop <- ISSUE-54-mod/#90-DETAIL-PhotoCalendar

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt
Title: MOD-Home
Jira Ticket: ISSUE-56
<br>
홈 - 전시회 리스트 페이징 처리
=> [PR] develop <- ISSUE-56-mod/#98-MOD-Home

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowerResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowingResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowerResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowingResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/interest/GetInterestResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/rating/GetRatingsResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetReviewsResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageInterestFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowerFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRatingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFollowerFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListFollowingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRatingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserViewModel.kt
Title: MOD-Profile 
Jira Ticket: ISSUE-58
<br>
- 마이프로필 - hasNextPage 적용 (페이지 처리)
- 타유저 - hasNextPage 적용 (페이지 처리)
=> [PR] develop <- ISSUE-58-mod/#101-MOD-Profile

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReviewApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/place/GetPlacesResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/GetReplyResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetReviewsExhibitionResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionPlaceFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ReviewFragment.kt
Title: MOD-Exhibition
Jira Ticket: ISSUE-57
<br>
전시회 - 리뷰 페이징 처리
리뷰 - 댓글 페이징 처리
전시장 - 전시회 페이징 처리
=> [PR] develop <- ISSUE-57-mod/#100-MOD-Exhibition

JeonsiLog/app/build.gradle, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/exhibition/GetCalendarExhibitionResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageDialog.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordSearchFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchResultAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchResultFragment.kt
Title: PhotoCalendarPage
Jira Ticket: ISSUE-60
<br>
- 전시회 불러오기 페이징
<br>
=> [PR] develop <- ISSUE-60-mod/#105-MOD-PhotoCalendarPage

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/place/SearchPlacesResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceItemAdapter.kt, JeonsiLog/app/src/main/res/layout/item_exihibition_search.xml
Title: SearPage
Jira Ticket:  ISSUE-62
<br>
전시회 주소추가
=> [PR] develop <- ISSUE-62-feat/#111-API-SearPage

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchItemAdapter.kt
Title: SearchPage
Jira Ticket: ISSUE-67
<br>
SearchPage 뒤로가기 오류 수정 
<br>
=> [PR] develop <- ISSUE-67-fix/#118-FIX-SearchPage

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageDialog.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/PhotoCalendatAdapter.kt, JeonsiLog/app/src/main/res/drawable/shape_calendar_cell_background.xml, JeonsiLog/app/src/main/res/layout/item_calendar_cell.xml, JeonsiLog/app/src/main/res/layout/view_load_page_dialog.xml
Title: PhotoCalendar
Jira Ticket:  ISSUE-63
<br>
포토캘린더 오늘 날짜 표시
<br>
=> [PR] develop <-ISSUE-63-feat/#112-PhotoCalendar

JeonsiLog/app/src/main/AndroidManifest.xml, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionPlaceFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordSearchFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/SearchResultFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/UserSearchItemAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/SearchViewModel.kt
Title: SearchPage
Jira Ticket: ISSUE-68
<br>
검색페이지 뒤로가기 처리
<br>
=> [PR] develop <- ISSUE-68-fix/#121-FIX-SearchPage

JeonsiLog/app/build.gradle, JeonsiLog/app/src/main/java/com/example/jeonsilog/base/BaseActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowerResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetMyFollowingResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowerResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/follow/GetOtherFollowingResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowerFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListFollowingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserListRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/extension/LodingDialog.kt, JeonsiLog/app/src/main/res/layout/dialog_loding.xml
Title: FIX-Profile
Jira Ticket: ISSUE-69
<br>
- 팔로잉 팔로우 목록에서 팔로잉 요청 및 취소 시 에러 수정
(프로필 이미지 Url이 null 오면 오류 발생)
-> Response에 null 값 가능하도록 수정함
- LodingDialog 추가
=> [PR] develop <- ISSUE-69-fix/#123-FIX-Profile

JeonsiLog/app/src/main/res/layout/dialog_network.xml, JeonsiLog/app/src/main/res/layout/item_other_user_rating.xml
Title: MOD-NetworkDialog 
Jira Ticket: ISSUE-71
<br>
- NetworkDialog - (취소 -> 닫기)
=> [PR] develop <- ISSUE-71-mod/#126-MOD-NetworkDialog

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageDialog.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/LoadPageRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/SingleFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/ExhibitionInfoItemAdapter.kt, JeonsiLog/app/src/main/res/layout/item_exhibition_info.xml
Title: PhotoCalendar
Jira Ticket: ISSUE-70
<br>
바텀시트비활성화 처리
<br>
=> [PR] develop <- ISSUE-70-fix/#125-FIX-PhotoCalendar

JeonsiLog/app/src/main/res/layout/item_exhibition_info.xml
Title: SearchPage
Jira Ticket:ISSUE-68
<br>
키워드 짤림 수정
<br>
=> ISSUE-68-fix/#121-FIX-SearchPage

JeonsiLog/app/src/main/java/com/example/jeonsilog/fcm/services/FirebaseMessagingService.kt
Title: FCM
Jira Ticket: ISSUE-74
<br>
FCM 푸시알림 쌓이지 않는 문제 해결
<br>
=> [PR] develop <- ISSUE-74-fix/#133-FIX-FCM

JeonsiLog/app/src/main/java/com/example/jeonsilog/base/BaseFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReviewApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetCheckReviewResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetReviewsExhibitionResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/PatchReviewRequest.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/review/ReviewRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/DialogWithIllus.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionReviewRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/PosterFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/WritingReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionViewModel.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionWritingViewModel.kt, JeonsiLog/app/src/main/res/layout/fragment_writing_review.xml, JeonsiLog/app/src/main/res/layout/item_exhibition_review.xml, JeonsiLog/app/src/main/res/values/strings.xml
Title: FIX-Exhibition
Jira Ticket: ISSUE-73
<br>
기존 감상평 띄우기, 수정하기 추가
감상평에 rating 없을때 별 안보이게 처리, rating 입력하면 보이게
알림 → 삭제된 감상평, 댓글 클릭 시 토스트 메시지 수정
call, homepage null 시 메시지 체크
감상평 상세에서 삭제하고 돌아가면 반영
감상평 아무것도 입력 안하면 등록 안되게 처리 - 한글자 이상일 때 등록 버튼 활성화
=> [PR] develop <- ISSUE-73-fix/#129-FIX-Exhibition

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt
Title: MyPage
Jira Ticket: ISSUE-75
<br>
MyPage BottomNav 수정
<br>
=> [PR] develop <- ISSUE-75-fix/#136-FIX-MyPage BottomNav 수정

JeonsiLog/app/src/main/res/layout/view_load_dialog.xml
Title: PhotoClaendar
Jira Ticket: ISSUE-76
<br>
포토캘린더 바텀시트 Dimming zone 중첩 수정
<br>
=> [PR] develop <- ISSUE-76-fix/#138-FIX-PhotoClaendar

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt, JeonsiLog/app/src/main/res/layout/fragment_review.xml, JeonsiLog/app/src/main/res/layout/item_review_reply.xml
Title: MOD-DefalutProfile
Jira Ticket: ISSUE-77
<br>
- 댓글 페이지 기본 프로필 이미지로 설정
- 프로필 사진 변경 시 encrytedPrefs에 저장되어 있는 이미지 Url Null로 변경
=> [PR] develop <- ISSUE-77-mod/#141-MOD-DefalutProfile

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/ReplyApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/reply/GetHasReplyResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/reply/ReplyRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/reply/ReplyRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/MainActivity.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ExhibitionReplyRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/exhibition/ReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/notification/NotificationRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/ExhibitionViewModel.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/GlobalApplication.kt, JeonsiLog/app/src/main/res/layout/activity_login.xml, JeonsiLog/app/src/main/res/layout/fragment_poster.xml, JeonsiLog/app/src/main/res/layout/fragment_review.xml, JeonsiLog/app/src/main/res/layout/fragment_signup.xml, JeonsiLog/app/src/main/res/layout/fragment_tos.xml, JeonsiLog/app/src/main/res/layout/fragment_writing_review.xml, JeonsiLog/app/src/main/res/values/strings.xml
Title: FIX-Exhibition
Jira Ticket: ISSUE-73
<br>
댓글 오류 수정
=> [PR] develop <- ISSUE-73fix/#129-FIX-Exhibition

JeonsiLog/app/build.gradle
Title: release 1.2.3
<br>
version code 6
version name 1.2.3
프로덕션 업로드용 빌드
=> [PR] main <- develop

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/review/GetReviewsResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserReviewFragment.kt, JeonsiLog/app/src/main/res/layout/item_my_page_review.xml, JeonsiLog/app/src/main/res/layout/item_other_user_review.xml
Title: FIX-Profile 
Jira Ticket: ISSUE-80
<br>
마이페이지 & 타유저 페이지에서 감상평 탭 들어갈 시 꺼지는 이슈
원인: GetReviewsResponse 수정됨
수정
- GetReviewsReponse.kt 수정
- 사용하는 곳
=> [PR] develop <- ISSUE-80-fix/#148-FIX-Proflie

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/search/RecordSearchFragment.kt
Title: ISSUE-81-fix/#151-FIX-PhotoCalendar
Jira Ticket: ISSUE-81 
<br>
검색 페이지 - 바텀 네비게이션 안보이는 문제 수정
=> [PR] develop <- ISSUE-81-fix/#151-FIX-PhotoCalendar

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminExhibitionFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminReviewFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/home/HomeRvAdapter.kt
Title: FIX-Admin
Jira Ticket: ISSUE-82
<br>
검색 결과 리스트 수정
홈 UI 개선
=> [PR] develop <- ISSUE-82-fix/#154-FIX-Admin

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/user/MyInfoResponse.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/user/UserRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/mypage/MyPageFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/otheruser/OtherUserFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/MyPageViewModel.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/OtherUserViewModel.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/widget/utils/CryptedPreferenceUtil.kt, JeonsiLog/app/src/main/res/layout/fragment_my_page.xml, JeonsiLog/app/src/main/res/layout/fragment_other_user.xml
Title: Profile Enhancement  
Jira Ticket: ISSUE-86
<br>
> 유저 정보 불러오기 응답 수정 (reviewCount, userLevel 추가)
> 마이페이이 레벨 추가
> 타 유저 페이지 레벨 추가
<br>
필요 시 관련 문서 기입
=> develop <- ISSUE-86-feat/#161-ProfileEnhancement

JeonsiLog/app/src/main/AndroidManifest.xml, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminPlaceFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchExhibitionFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchExhibitionRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchPlaceFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchPlaceRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchUserFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchUserRvAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminSearchVpAdapter.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminUserFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/viewmodel/AdminViewModel.kt, JeonsiLog/app/src/main/res/layout/fragment_admin_search.xml, JeonsiLog/app/src/main/res/layout/fragment_admin_search_exhibition.xml, JeonsiLog/app/src/main/res/layout/fragment_admin_search_place.xml, JeonsiLog/app/src/main/res/layout/fragment_admin_search_user.xml, JeonsiLog/app/src/main/res/layout/fragment_admin_user.xml, JeonsiLog/app/src/main/res/layout/item_exihibition_search.xml, JeonsiLog/app/src/main/res/values/strings.xml
Title: Admin-Search-Enhancement
Jira Ticket: ISSUE-88
<br>
>전시회 검색
>전시장 검색
> 유저 검색
<br>
=> develop <- ISSUE-88-feat/#164-Admin-Search-Enhancement

JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/api/StopApi.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/data/remote/dto/stop/StopReq.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/stop/StopRepository.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/repository/stop/StopRepositoryImpl.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminUserFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/DialogStopReason.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/DialogStopSelector.kt, JeonsiLog/app/src/main/res/drawable/selector_radio_btn.xml, JeonsiLog/app/src/main/res/drawable/shape_stop_btn.xml, JeonsiLog/app/src/main/res/layout/dialog_stop_reason.xml, JeonsiLog/app/src/main/res/layout/dialog_stop_selector.xml, JeonsiLog/app/src/main/res/layout/fragment_admin_user.xml
Title: ActivitySuspended
Jira Ticket:  ISSUE-89
<br>
>다이얼로그 추가
> Stop API 추가
<br>
필요 시 사용 
<br>
=> develop <- ISSUE-89-feat/#164-ActivitySuspended

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminManagingFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminReportFragment.kt, JeonsiLog/app/src/main/java/com/example/jeonsilog/view/admin/AdminReportRvAdapter.kt, JeonsiLog/app/src/main/res/layout/fragment_admin_report.xml
Title: AdminEnhancement
Jira Ticket: ISSUE-90
<br>
- QA
- report - bottom margin 수정
- managing list 초기 세팅 수정
=> [PR] develop <- ISSUE-90-feat/#169-AdminEnhancement

JeonsiLog/app/src/main/java/com/example/jeonsilog/view/photocalendar/CaptionDialog.kt
Title: 캡션 입력 불가 수정
Jira Ticket:ISSUE-91
<br>
캡션 입력 불가 수정
=> ISSUE-91 [fix] 캡션 입력 불가 수정
